name: Release pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - run: echo "A new release will be published with name ${GITHUB_REF#refs/*/}"
